### ISSUE TITLE
[翻译]项目管理委员（PMC）针对商标的管理职责

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/translation#10]
这篇文章明确 PMC在管理商标需要做的事情
http://www.apache.org/foundation/marks/pmcs
翻译的文章需要Markdown格式，提交到 放置在 ASF/policy/marks 目录中。

**Comment by sunshinemingo** [comment]
I want to have a try in order to help me understand the workflow of translation better.

**Comment by WillemJiang** [comment]
The PR is merged into master branch. Thanks the contribution of @sunshinemingo.
