### ISSUE TITLE
[翻译] ASF许可证常见问题

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/translation#17]
Apache 软件许可协议作为宽松的商业友好的许可协议被业界广泛使用。 本文涵盖了ASF软件的许可常见问题，里面涵盖了很多与Apache软件许可协议使用相关的常见问题，以及Apache软件基金会旗下软件许可操作相关的内容。

原文链接： http://www.apache.org/foundation/license-faq.html

翻译收益：了解ASF 软件许可指定的相关背景知识，可以加深对软件许可协议的认识。

**Comment by JesseZhou-1** [comment]
I will take it

**Comment by WillemJiang** [comment]
@JesseZhou-1  I just assigned the task to you.

**Comment by WillemJiang** [comment]
#26 代码已合入， 感谢 @JesseZhou-1 的贡献。
