### ISSUE TITLE
[翻译] Apache产品发版规则

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/translation#18]
Apache软件基金会为了保证软件发布的合规，专门制定了这个发版规则。 
本文从定义Apache的发版（release）， 结合发版发布件，以及Apache项目发版需要准备的 LICENSE  和 NOTICE 文件，详细介绍了版本发布需要注意的内容。 最后结合发布过程中遇到的常见问题给出相关的指导建议。

**翻译收益** ：本文是Apache项目发布经理必读文章，对发布一个合规的开源项目有很大的指导意义。

**原文链接** ：http://www.apache.org/legal/release-policy.html

**难度** ： 中高级
**提交路径** ：apache/license

**Comment by taskmgr** [comment]
I ‘d like to translate this.

**Comment by WillemJiang** [comment]
Merged the PR into master branch.
