### ISSUE TITLE
[翻译] Apache产品第三方License使用指导

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/translation#19]
Information related to third-party license use in Apache Products
原文链接： http://www.apache.org/legal/resolved.html

翻译收益：对各大流行License与Apache License的之间的关系有更深刻的认识。
提交路径：apache/license
难度：*****

**Comment by WillemJiang** [comment]
@missing-9  麻烦你在这个issue上面加一个comment， 这样可以把这个任务分配给你。

**Comment by missing-9** [comment]
是在这里留下comment吗？

**Comment by missing-9** [comment]
这个issue我认领一下啦~

**Comment by missing-9** [comment]
“ASF 3RD PARTY LICENSE POLICY”翻译已经完成。 @WillemJiang 烦请review😀。

**Comment by JesseZhou-1** [comment]
本issue已完成，感谢 @missing-9 的贡献
