### ISSUE TITLE
[翻译] 代码头和Copyright声明

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/translation#20]
Source Header and Copyright Notice Policy
**原文链接**：http://www.apache.org/legal/src-headers.html

提交路径： apache/license
翻译收益： 了解代码头声明的意义， 以及Copyright 声明需要注意的内容

**Comment by QuakeWang** [comment]
I want to have a try.

**Comment by WillemJiang** [comment]
翻译已合并。
