### ISSUE TITLE
[翻译] 贡献者协议常见问题

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/translation#21]
Questions related to signing our Contributor License Agreements
**原文链接**： https://www.apache.org/licenses/cla-faq.html

**Comment by JesseZhou-1** [comment]
I am interested in this article, I will work on its translation.

**Comment by WillemJiang** [comment]
@JesseZhou-1 I assigned the task to you.

**Comment by JesseZhou-1** [comment]
本 issue已完成
