### ISSUE TITLE
翻译 Trillions and Trillions Served - Apache Everywhere

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/translation#3]
作为 Apache记录片 Trillions and Trillions Served [先导介绍](https://youtu.be/nXtIti9jMFI)， 片中提取很多有关Apache Way的解释的内容，翻译此字幕可以帮助大家对Apache之道有一个更深入的理解。

难点： 目前这段视频没有提供YouTube的字幕。

**Comment by WillemJiang** [comment]
[Apache_Everywhere-nXtIti9jMFI.mp3-文稿-转写结果.txt](https://github.com/alc-beijing/translation/files/5286855/Apache_Everywhere-nXtIti9jMFI.mp3-.-.txt)
上传文字稿， 后续需要按照时间线把内容分割出来。

**Comment by missing-9** [comment]
I'd like to have a try☺

**Comment by WillemJiang** [comment]
@missing-9 英文字幕文件已上传， 现在需要把英文翻译成中文，详情请参考 #49

**Comment by missing-9** [comment]
好的，我看看。
