### ISSUE TITLE
[翻译] Apache 文档 Assembling LICENSE and NOTICE files 中文翻译计划

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/translation#41]
## 翻译必读

* **工作流程：** https://github.com/alc-beijing/translation/blob/master/docs/WORKFLOW.md
* **翻译指南：** https://github.com/alc-beijing/translation/blob/master/docs/GUIDE.md
* **术语表：** https://github.com/alc-beijing/translation/blob/master/docs/GLOSSARY.md

## 文档信息

* **原文标题：**  Assembling LICENSE and NOTICE files 
* **原文链接：** https://infra.apache.org/licensing-howto.html
* **中文链接：** https://github.com/alc-beijing/translation/tree/master/apache/license/licensing-howto.md

**Comment by missing-9** [comment]
![Uploading image.png…]()

**Comment by missing-9** [comment]
https://github.com/alc-beijing/translation/blob/master/docs/WORKFLOW.md

**Comment by WillemJiang** [comment]
@missing-9  Just fixed the broken link.

**Comment by missing-9** [comment]
> @missing-9 Just fixed the broken link.

It's OK now.

**Comment by WillemJiang** [comment]
@missing-9  Do you want to give it a try? Please let me know if you have any question about this task.

**Comment by missing-9** [comment]
> @missing-9 Do you want to give it a try? Please let me know if you have any question about this task.

yes ! I wanna to try ! ☺

**Comment by missing-9** [comment]
文档信息——中文链接 the link is 404.

**Comment by WillemJiang** [comment]
> 文档信息——中文链接 the link is 404.

这个是期望你提交的markdown文件的路径，现在没有提交，访问这个链接肯定是404.

**Comment by missing-9** [comment]
好的。

**Comment by WillemJiang** [comment]
是的， 现在License相关的任务都已经分配完了。

**Comment by missing-9** [comment]
ok

**Comment by missing-9** [comment]
leave a comment..

**Comment by WillemJiang** [comment]
Thanks the contribution of @missing-9 , the PR #48 is merged.
