### ISSUE TITLE
[错误] WORKFLOW图片序号错误

### ISSUE THREAD

**Issue by QuakeWang** [alc-beijing/translation#44]
在关于描述 workflow 过程的图片中，`创建 PR` 的序号为 `87`，是否应该更改为 `7.`？？
![workflow](https://raw.githubusercontent.com/alc-beijing/translation/75520118494869f68dc0d9033f394a6de6a2a13a/docs/images/WORKFLOW.svg)

**Comment by WillemJiang** [comment]
@hanyouqing  Could you take a look at it?

**Comment by hanyouqing** [comment]
> @hanyouqing Could you take a look at it?

done: https://github.com/alc-beijing/translation/pull/46
