### ISSUE TITLE
[翻译] Apache Everywhere 字幕翻译

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/translation#49]
## 翻译必读

* **工作流程：** https://github.com/alc-beijing/translation/blob/master/docs/WORKFLOW.md
* **翻译指南：** https://github.com/alc-beijing/translation/blob/master/docs/GUIDE.md
* **术语表：** https://github.com/alc-beijing/translation/blob/master/docs/GLOSSARY.md
* * **格式语法：** https://docs.github.com/cn/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax

## 文档信息

* **原文标题：** Apache Everywhere
* **原文链接：** https://www.youtube.com/watch?v=nXtIti9jMFI
* **提交路径：** translation/subtitles/ApacheEverywhere.srt
* **翻译收益：** 可以深入了解Apache成员的访谈，进一步理解ASF成立的背景，以及大家对ASF的看法
* **翻译难度：** 中等

字幕总共 87行，任务可以分成两份，1-43 以及 44-87 欢迎大家认领。

**Comment by Jennifer88huang** [comment]
@WillemJiang I'd like to help review the translation~

**Comment by JesseZhou-1** [comment]
I could give give it a try, I will start with the first half.

**Comment by WillemJiang** [comment]
Just close this issue as the srt is merged.
