### ISSUE TITLE
英文原文文章疑似错误

### ISSUE THREAD

**Issue by missing-9** [alc-beijing/translation#54]
在翻译时发现原文有一处疑似错误，可否帮忙确认下单词拼写是否应该是“Including”，而不是“Incuding”呢？

文章链接：https://www.apache.org/legal/resolved.html#build-tools

![image](https://user-images.githubusercontent.com/29998376/108596524-8cea1c00-73c0-11eb-80d6-3e93c6750ad9.png)

**Comment by missing-9** [comment]
我觉得应该是“Including”。“Incuding”没有查到比较合适的含义。感觉是单词拼写错误。有译友有兴趣来一起验证下嘛😂

**Comment by WillemJiang** [comment]
这是一个typo问题， 只是我在网站上没有找到如何提issue和PR的地方。
建议@missing-9 可以给 dev@community.apache.org 发一封邮件问一下这个错怎么修复？

**Comment by missing-9** [comment]
OK

**Comment by missing-9** [comment]
Just close this issue as the email is sent.

**Comment by missing-9** [comment]
源网站错误已经更正过来了。

![image](https://user-images.githubusercontent.com/29998376/110140429-0ba67680-7e0f-11eb-832b-bb5d6af0033b.png)

**Comment by JesseZhou-1** [comment]
牛牛牛🐂
