### ISSUE TITLE
[翻译] “Apache 成立22周年”报道文章 翻译

### ISSUE THREAD

**Issue by JesseZhou-1** [alc-beijing/translation#58]
## 翻译必读

* [ **工作流程**]( https://github.com/alc-beijing/translation/blob/master/docs/WORKFLOW.md)
* [**翻译指南**](https://github.com/alc-beijing/translation/blob/master/docs/GUIDE.md)
* [**术语表**](https://github.com/alc-beijing/translation/blob/master/docs/GLOSSARY.md)
* *  #[**格式语法**](https://docs.github.com/cn/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax)

## 文档信息

* **原文标题：** The Apache® Software Foundation Celebrates 22 Years of Open Source Innovation "The Apache Way"
* **原文链接：** https://www.globenewswire.com/news-release/2021/03/24/2198532/17401/en/The-Apache-Software-Foundation-Celebrates-22-Years-of-Open-Source-Innovation-The-Apache-Way.html
* **提交路径：** translation/apache.md

**Comment by Asxing** [comment]
pls assign me, thanks.

**Comment by JesseZhou-1** [comment]
sure

**Comment by marklightning** [comment]
I have finished the translation

**Comment by JesseZhou-1** [comment]
@Asxing hi~ Mark just finished the translation, would you like to help review it?

**Comment by WillemJiang** [comment]
Merged PR #61  into master branch.
