### ISSUE TITLE
翻译ASF孵化器指南

### ISSUE THREAD

**Issue by jnjt115** [alc-beijing/translation#6]
### ASF孵化器指南
https://incubator.apache.org/cookbook/

**成为ASF顶级项目的步骤**
步骤 | 内容 | 详情
-- | -- | --
1 | 与孵化器沟通 | 孵化器PMC管理孵化器，帮助项目孵化。
2 | 寻找接口人（champion）和孵化导师，讨论并准备孵化方案 | 项目要进入孵化器，需要一个接口人和至少2-3个导师，只有孵化器PMC中的成员可以担任这两种角色。
3 | 创建孵化方案 | 接口人会帮助项目准备孵化方案，该方案将用于下一步与孵化器PMC的讨论。方案可以根据模板编写，需要包含几个标准部分。
4 | 与孵化器PMC讨论孵化方案 | 方案准备好后，项目代表要将其发送至general@incubator.a.o邮箱，孵化器PMC会对该方案进行讨论。
5 | 如有需要，完善方案中初始提交者和导师列表 | -
6 | 如有需要，基于孵化器PMC的反馈完善方案 | -
7 | 孵化器PMC对方案进行投票 | 讨论阶段结束后，接口人或项目代表会在general@incubator.a.o邮件列表中启动【投票】进程，投票按照ASF的投票规则进行。
8 | 设置该项目的基础设施（JIRA等） | 如果孵化器PMC同意接受该项目，就可建立该项目的基础设施了，该过程通常由接口人或导师进行推动，如果社区成员熟悉该操作，也可由社区成员来推动。
9 | 导入初始代码 | 企业捐赠的项目，在导入初始代码前，需要提交软件授权协议（SGA）或企业贡献者许可协议（CCLA）；个人捐赠的项目，在导入初始代码前，需要主要贡献者提交个人贡献者许可协议（ICLA）或SGA。导入过程中，需要检查和报告代码中受美国出口管制法管制的密码技术。除此以外，代码还需要按照Apache模板，进行清理和重新打包。
10 | 围绕该项目的代码构建社区 | 包括投票产生新的提交者和PPMC成员（Podling Project Management Committee）。
11 | 发布项目，记录并完善发布过程 | 在孵化期间，预计将发布多个版本，这些版本将逐渐符合ASF发布政策。完全合规的发布是项目毕业的条件之一。孵化中的项目进行发布还必须在任何发布文件名中包含“incubating”一词，并根据孵化器发布指南包含免责声明或免责声明-WIP，以防止对项目状态产生任何混淆。由于孵化中的项目还不是“真正的”ASF项目，所以设定正确的期望值是很重要的。   孵化中的项目版本发布需要两次投票，一次是在开发者邮件列表上进行的投票，如果PPMC成员中至少有3个赞成票（+1），并且赞成票比反对票（-1）多就算通过了。第二次是在孵化器常规邮件列表上进行的投票，这次投票由孵化器PMC进行投票。   Apache发布仅包含源代码，但是项目通常也会分发一些编译过的软件包。软件源代码发布是发布重点，所有分发的编译过的软件包均基于这些发布的“正式”的源代码。
12 | 准备毕业，与导师一起评估项目的准备情况 | 准备毕业的项目需要根据ASF提供的成熟度模型进行自我评估，这可以帮助发现在孵化过程中被忽略的事务。
13 | 将商标转让给ASF | 将代码捐赠给ASF的企业或个人，如果持有该项目需要的商标，则需在项目毕业前，将商标转让给ASF。
14 | 与孵化器PMC讨论毕业 | 如果社区和导师根据自我评估认为项目已经做好准备，可以毕业，会在孵化器常规邮件列表上开始一个【讨论】进程，提议毕业并请求孵化器PMC审查该项目。
15 | 孵化器PMC进行毕业投票 | 毕业提议的【讨论】进程结束后，孵化器常规邮件列表上会开始一个【投票】进程，孵化器PMC对该项目进行投票，投票依据ASF投票规则进行。
16 | ASF董事会决议 | 孵化器投票通过后，将会创建董事会决议进程并发送给ASF董事会，供董事会投票。董事会每月第三个周三会召开会议，会上会对此类决议进行投票，投票结果即刻生效。
17 | 毕业后的任务 | 毕业后，项目需要在孵化器状态页面上更新状态，并对其资源和流程进行一些更改。

**Comment by WillemJiang** [comment]
@jnjt115 建议把https://incubator.apache.org/cookbook/ 翻译出来， 文件可以放到 apache/incubator/cookbook 目录中。

**Comment by WillemJiang** [comment]
@jnjt115 你整理的内容挺好的， 可以考虑写在alc-site上面发一篇文章，把ASF项目孵化需要做的事情用列表的方式展示出来。

**Comment by tedliu1** [comment]
Incubator Cookbook https://incubator.apache.org/cookbook/ 我认领吧！ @jnjt115 可以和我分工合作

**Comment by WillemJiang** [comment]
@jnjt115 提交的是个精简版。 欢迎@tedliu1 加入，翻译好的文件可以放到 apache/incubator/cookbook 目录中。

**Comment by tedliu1** [comment]
@WillemJiang 我可以直接翻译，不需要再 fork 到本地吗？

**Comment by tedliu1** [comment]
@jnjt115 你这个表格可以发给我吗？tedliu1@yahoo.com 或是 微信号 tedliu002

**Comment by WillemJiang** [comment]
我刚刚把 @jnjt115 的贡献合并到repo中， @tedliu1 你可以通过页面 https://github.com/alc-beijing/translation/blob/master/apache/incubator/cookbook-zh.md 选择编辑直接提交内容， github会自动生成PR的。

**Comment by tedliu1** [comment]
@WillemJiang Ahah, 太棒了，谢谢!
This is great. Thanks!

**Comment by WillemJiang** [comment]
We can close this task as all the changes are merged.
