### ISSUE TITLE
[翻译] Apache 软件基金会品牌管理指南

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/translation#7]
原文地址 http://www.apache.org/foundation/marks/guide
为了翻译校对方便，需要把文件提交到  ASF/policy/marks 目录下

**Comment by taskmgr** [comment]
我打算翻译这篇文章，其他小伙伴请注意不要重复工作呀~

**Comment by WillemJiang** [comment]
赞， 启动你的贡献。

**Comment by WillemJiang** [comment]
多谢@taskmgr的贡献， 翻译文档已合并， 后续会提交至ALC Beijing公众号发布。
