### ISSUE TITLE
[翻译] Apache项目毕业指南

### ISSUE THREAD

**Issue by tuohai666** [alc-beijing/translation#77]
Guide :: Guide to Successful Graduation
原文链接：http://incubator.apache.org/guides/graduation.html

文档提交至 apache/incubator

翻译过程中发现原文中有2个需要优化的地方，已经通过JIRA和邮件列表反馈。如果以后原文有更新，我会同步到翻译的文档中，处理进展可以在此跟踪：
https://issues.apache.org/jira/browse/INCUBATOR-265
https://lists.apache.org/thread.html/rc5ff195aebc1d662549c690532a17dcd330d9847c843a4701431bce2%40%3Cgeneral.incubator.apache.org%3E

**Comment by tuohai666** [comment]
文档中两处优化已经merge到incubator，翻译版也完成同步了。

**Comment by WillemJiang** [comment]
翻译内容已合并。
