### ISSUE TITLE
毕业指南原文疑似错误

### ISSUE THREAD

**Issue by tuohai666** [alc-beijing/translation#79]
在翻译毕业指南时，发现原文的一个疑似错误。
原文链接： http://incubator.apache.org/guides/graduation.html#whether_to_graduate_to_subproject_or_to_top_level_project

第二段：
Graduation as a subproject is only possible if the subproject still falls within the scope of the project and requires the consent of the project PMC. **Graduation as a project** requires the formation of the new project by the Board.

此处如果将**Graduation as a project**改为**Graduation as a top level project**则符合上下文。

**Comment by tuohai666** [comment]
我再JIRA上创建了一个issue

**Comment by kezhenxu94** [comment]
已经合并
