### ISSUE TITLE
[翻译]Apache商标使用管理原则

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/translation#8]
这篇文章定义了使用Apache商标的几种常见场景，以及在这些场景需要注意的事项
http://www.apache.org/foundation/marks/

翻译的文章需要Markdown格式，提交到 放置在 ASF/policy/marks 目录中。

**Comment by Ns614742780** [comment]
I'd like to translate this page.

**Comment by WillemJiang** [comment]
@Ns614742780  Thanks for looking into this task. 
Please let me know if you have any question about it.

**Comment by WillemJiang** [comment]
Here is the PR of this issue,  https://github.com/alc-beijing/translation/pull/15.

**Comment by WillemJiang** [comment]
Thx the contribution of @Ns614742780, the translated file is merged.
