### ISSUE TITLE
[翻译] Apache软件基金会安全报告

### ISSUE THREAD

**Issue by JesseZhou-1** [alc-beijing/translation#82]
## 翻译必读

* [ **工作流程**]( https://github.com/alc-beijing/translation/blob/master/docs/WORKFLOW.md)
* [**翻译指南**](https://github.com/alc-beijing/translation/blob/master/docs/GUIDE.md)
* [**术语表**](https://github.com/alc-beijing/translation/blob/master/docs/GLOSSARY.md)
* *  #[**格式语法**](https://docs.github.com/cn/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax)

## 文档信息

Apache在2020年1月十号发布了2021年的Apache所有软件的安全报告，系统的检视了软件的关键指标、具体的漏洞以及ASF项目的用户受到安全问题影响的最常见方式。

* **原文标题：** Apache Software Foundation Security Report: 2021
* **原文链接：** The_original_link_of_the_documentation](https://blogs.apache.org/foundation/entry/apache-software-foundation-security-report2

**Comment by JiaoYinger** [comment]
报名参与

**Comment by JesseZhou-1** [comment]
好的👌

**Comment by WillemJiang** [comment]
报告内容已经发布公众号。
