### ISSUE TITLE
[翻译] Apache 软件基金会 2019 安全报告

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/translation#85]
## 翻译必读

* [ **工作流程**]( https://github.com/alc-beijing/translation/blob/master/docs/WORKFLOW.md)
* [**翻译指南**](https://github.com/alc-beijing/translation/blob/master/docs/GUIDE.md)
* [**术语表**](https://github.com/alc-beijing/translation/blob/master/docs/GLOSSARY.md)
* *  #[**格式语法**](https://docs.github.com/cn/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax)

## 文档信息
Apache软件基金会连续三年（2019-2021）发布了其下的软件的安全报告，这是2019年的安全报告。

原文标题： Apache Software Foundation Security Report: 2019
原文链接： The_original_link_of_the_documentation](https://blogs.apache.org/foundation/entry/apache-software-foundation-security-report)
翻译件提交路径： apache/securityreport/

**Comment by JiaoYinger** [comment]
please assign me
