### ISSUE TITLE
[翻译] Apache Security 2022 年度报告

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/translation#89]
## 翻译必读

* [ **工作流程**]( https://github.com/alc-beijing/translation/blob/master/docs/WORKFLOW.md)
* [**翻译指南**](https://github.com/alc-beijing/translation/blob/master/docs/GUIDE.md)
* [**术语表**](https://github.com/alc-beijing/translation/blob/master/docs/GLOSSARY.md)
* *  #[**格式语法**](https://docs.github.com/cn/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax)

## 文档信息

* **原文标题：** ASF Security Report: 2022
* **原文链接：** https://blogs.apache.org/security/entry/asf-security-report-2022
* **提交路径：** apache/securityreport/asf-security-report-2022
* **翻译收益：** 了解ASF去年的安全问题
* **翻译难度：** ***

**Comment by wjsvec** [comment]
Please assign it to me☺️
