### ISSUE TITLE
[翻译]Apache下游项目的品牌使用原则

### ISSUE THREAD

**Issue by WillemJiang** [alc-beijing/translation#9]
大家基于Apache的项目会做一些衍生的发行版，在这些衍生发行版中需要注意哪些事情呢？

注意： 这篇文章还处于初稿阶段。
http://www.apache.org/foundation/marks/downstream.html

**Comment by QuakeWang** [comment]
我尝试翻译一下这篇初稿：）

**Comment by QuakeWang** [comment]
@WillemJiang In which directory should I put this article?

**Comment by WillemJiang** [comment]
@QuakeWang 文章放置到 /apache/marks/ 下面。

**Comment by WillemJiang** [comment]
代码已合入 #25 ， 非常感谢 @QuakeWang 的贡献。
